---
technitium_dns_prerequisite_packages:
  - curl
  - ca-certificates
  - tar

technitium_dns_dotnet_packages:
  - aspnetcore-runtime-8.0

technitium_dns_dotnet_binary: /usr/bin/dotnet

technitium_dns_dns_client_packages:
  - bind-utils

technitium_dns_firewall_packages:
  - firewalld

technitium_dns_firewall_default_backend: firewalld

